### PR TITLE
Case sensitive path merge and remove getFirstCaseSensitiveChar

### PR DESCRIPTION
**Pull request by Leinnan**
Now its better? :smiley:

### CODE REVIEW

**Comment by degenerated1123** [comment]
Nice! We will need another function for the folders, since they can vary as well.

**Comment by Leinnan** [comment]
Now You can put the better world-shader into the right folder, which displays the "shadows" baked into the worldmeshes vertices. :earth_asia:

**Comment by degenerated1123** [comment]
I'll do it later. I have added code for a physicsengine and it isn't quite done yet. Don't want to push all this right now

**Comment by Leinnan** [comment]
Okey.

**Pull request merged**
