### PR TITLE
Aqua

### PR DESCRIPTION
**Pull request by Aquaz**
Implemented surface recognition under NPCs feet and basic swimming (there is no transitioning between ground and water yet and animation change is immediate.

I tried implementing improvised memoization system for caching functions output but applying caching to the surface type retrieval function resulted in no performance improvement, single invocation consumes roughly 15-20 microseconds with and without caching so I decided to leave it as it is for now. The generic memoization technique should be implemented either way for other use cases but is not crucial for this change.

### CODE REVIEW

**Comment by CarnageMarkus** [comment]
Does this apply even if you spawn hundreds of npcs ?

**Comment by Aquaz** [comment]
I have performed the additional measurements to ensure the current performance is sufficient, simply returning from the function most of the time and performing the calculation (raytrace and triangle retrieval) once in 30 runs (which sort of, simulates caching). The results are a lot better as I realized there was an error in the previous measurement, I was profiling also other functions in addition to the getsurfacematerial by a mistake, now the outcome is:

With simulated caching 
Info: Duration: 3201 nanoseconds on average
Without caching
Info: Duration: 200 nanoseconds on average

The above results make sense now. In conclusion, caching helps and can be applied but is not necessary for now, I will implement simple and generic memoization system and when that's done the function can take advantage of it, but for now I don't think there is a need to implement a hacked caching just for this method, for example, even if there were 1000 NPCs performing it in their game loop, the combined execution time would be 3.2 ms on average (versus 200 microseconds with caching).

**Comment by degenerated1123** [comment]
With caching I actually meant to just save the hit polygon index for other features to use. Footstep-sounds, for example.

There already is a trace down every frame, performed by "placeOnGround". Would be cool if you could combine those two.

Haven't tested this yet, but will do as soon as I can :)

Also, a little nitpick: `ZenLoad::zCMaterialData GetMatData(size_t triangleIdx);`, methods should start with a lowercase letter ;)

**Comment by Aquaz** [comment]
Ah right, the function name is an annoying habit from other projects I'm involved into, I tried paying extra attention when writing something that differs in code style between projects but sometimes it just happens subconsciously :D I will change both things you mentioned when I get back home from work tomorrow :)

**Comment by degenerated1123** [comment]
Awesome!

**Comment by CarnageMarkus** [comment]
@degenerated1123  maybe you could add coding conventions for this project into reade ?

**Pull request merged**
